/* ============================================
   OSINT RESOURCES DATA
   Comprehensive list of OSINT tools and resources
   ============================================ */

export interface OsintResource {
  id: string
  name: string
  url: string
  description: string
  category: string
  tags: string[]
}

export const osintResources: OsintResource[] = [
  // OSINT SEARCH ENGINES & RECONNAISSANCE
  {
    id: "1",
    name: "Shodan",
    url: "https://www.shodan.io",
    description:
      "Search engine for Internet-connected devices. Find exposed databases, webcams, routers, and industrial control systems.",
    category: "OSINT Search Engines",
    tags: ["iot", "devices", "network", "security"],
  },
  {
    id: "2",
    name: "Censys",
    url: "https://censys.io",
    description:
      "Internet-wide scanning and analysis platform. Discover and monitor internet assets and attack surfaces.",
    category: "OSINT Search Engines",
    tags: ["scanning", "network", "certificates", "security"],
  },
  {
    id: "3",
    name: "Hunter.io",
    url: "https://hunter.io",
    description:
      "Find professional email addresses associated with a domain. Verify email deliverability and find contact information.",
    category: "OSINT Search Engines",
    tags: ["email", "contacts", "verification", "domain"],
  },
  {
    id: "4",
    name: "Maltego",
    url: "https://www.maltego.com",
    description:
      "Interactive data mining tool for link analysis and visualization. Map relationships between people, companies, and infrastructure.",
    category: "OSINT Search Engines",
    tags: ["visualization", "analysis", "relationships", "mapping"],
  },
  {
    id: "5",
    name: "SpiderFoot",
    url: "https://www.spiderfoot.net",
    description:
      "Automated OSINT reconnaissance tool. Gather intelligence about IP addresses, domains, email addresses, and more.",
    category: "OSINT Search Engines",
    tags: ["automation", "reconnaissance", "scanning", "intelligence"],
  },
  {
    id: "35",
    name: "Recon-ng",
    url: "https://github.com/lanmaster53/recon-ng",
    description: "Full-featured reconnaissance framework. Modular design for web-based open source reconnaissance.",
    category: "OSINT Search Engines",
    tags: ["framework", "reconnaissance", "modular", "automation"],
  },
  {
    id: "36",
    name: "theHarvester",
    url: "https://github.com/laramies/theHarvester",
    description:
      "Gather emails, subdomains, hosts, employee names, and more from public sources. Essential OSINT tool.",
    category: "OSINT Search Engines",
    tags: ["email", "subdomain", "harvesting", "reconnaissance"],
  },
  {
    id: "59",
    name: "Mach9ne OSINT",
    url: "https://mach9ne.xyz/osint/",
    description: "Comprehensive OSINT toolkit and resource collection. Multiple tools for intelligence gathering.",
    category: "OSINT Search Engines",
    tags: ["toolkit", "framework", "tools", "collection"],
  },
  {
    id: "60",
    name: "OSINT Tool",
    url: "https://www.osint-tool.com/",
    description: "All-in-one OSINT platform with multiple investigation tools. Email, phone, and social media lookup.",
    category: "OSINT Search Engines",
    tags: ["platform", "investigation", "lookup", "tools"],
  },
  {
    id: "61",
    name: "OathNet",
    url: "https://oathnet.org/",
    description: "OSINT framework and resource directory. Curated collection of intelligence gathering tools.",
    category: "OSINT Search Engines",
    tags: ["framework", "directory", "resources", "tools"],
  },
  {
    id: "62",
    name: "CSINT.dev",
    url: "https://csint.dev/",
    description: "Cybersecurity intelligence platform. Tools for threat intelligence and OSINT research.",
    category: "OSINT Search Engines",
    tags: ["cybersecurity", "threat-intel", "platform", "research"],
  },
  {
    id: "63",
    name: "OSINT Deck",
    url: "https://osintdeck.org/",
    description: "Visual OSINT tool dashboard. Organized collection of intelligence gathering resources.",
    category: "OSINT Search Engines",
    tags: ["dashboard", "visual", "collection", "tools"],
  },
  {
    id: "64",
    name: "OSINT Rocks",
    url: "https://osint.rocks/",
    description: "Curated OSINT resource library. Tools, techniques, and guides for open source intelligence.",
    category: "OSINT Search Engines",
    tags: ["library", "resources", "guides", "techniques"],
  },
  {
    id: "65",
    name: "Analyst Research Tools",
    url: "https://analystresearchtools.com/",
    description: "Professional OSINT toolkit for analysts. Comprehensive collection of investigation resources.",
    category: "OSINT Search Engines",
    tags: ["analyst", "professional", "toolkit", "investigation"],
  },
  {
    id: "66",
    name: "OSINT Framework",
    url: "https://osintframework.com/",
    description:
      "The definitive OSINT resource tree. Organized hierarchy of intelligence gathering tools and techniques.",
    category: "OSINT Search Engines",
    tags: ["framework", "tree", "comprehensive", "definitive"],
  },

  // BREACH DATABASES & DATA LEAKS
  {
    id: "6",
    name: "Have I Been Pwned",
    url: "https://haveibeenpwned.com",
    description:
      "Check if your email or phone has been compromised in a data breach. Database of billions of breached accounts.",
    category: "Breach Sites",
    tags: ["breach", "passwords", "email", "security"],
  },
  {
    id: "7",
    name: "DeHashed",
    url: "https://dehashed.com",
    description:
      "Search engine for leaked databases. Find credentials, personal information, and breach data across multiple sources.",
    category: "Breach Sites",
    tags: ["credentials", "leaks", "breach", "database"],
  },
  {
    id: "8",
    name: "LeakCheck",
    url: "https://leakcheck.io",
    description:
      "Database of leaked credentials and personal information. Search by email, username, password hash, or domain.",
    category: "Breach Sites",
    tags: ["leaks", "credentials", "breach", "search"],
  },
  {
    id: "9",
    name: "Snusbase",
    url: "https://snusbase.com",
    description:
      "Comprehensive breach database with advanced search capabilities. Access to billions of leaked records.",
    category: "Breach Sites",
    tags: ["breach", "database", "search", "leaks"],
  },
  {
    id: "10",
    name: "IntelX",
    url: "https://intelx.io",
    description: "Search engine and data archive. Access to breached databases, leaked documents, and darknet content.",
    category: "Breach Sites",
    tags: ["archive", "breach", "darknet", "search"],
  },
  {
    id: "37",
    name: "Leak-Lookup",
    url: "https://leak-lookup.com",
    description: "Search through data breaches and leaks. Find compromised credentials and personal information.",
    category: "Breach Sites",
    tags: ["breach", "lookup", "credentials", "leaks"],
  },
  {
    id: "57",
    name: "Breach.vip",
    url: "https://breach.vip/",
    description:
      "Premium breach database with extensive leak collections. Search for compromised credentials and data.",
    category: "Breach Sites",
    tags: ["breach", "premium", "database", "leaks"],
  },
  {
    id: "58",
    name: "Breach Directory",
    url: "https://breachdirectory.org/privacy",
    description:
      "Free breach search engine with privacy focus. Check if your data has been compromised in known breaches.",
    category: "Breach Sites",
    tags: ["breach", "privacy", "search", "free"],
  },
  {
    id: "91",
    name: "MostWantedHF",
    url: "https://mostwantedhf.info/index.php",
    description: "Hacking forum and breach database. Community discussions and leaked data sharing.",
    category: "Breach Sites",
    tags: ["breach", "forum", "leaks", "hacking"],
  },

  // HACKING FORUMS & COMMUNITIES
  {
    id: "17",
    name: "RaidForums (Archive)",
    url: "https://raidforums.com",
    description: "Historical database leak forum (now seized). Archive of discussions and leaked databases.",
    category: "Hacking Forums",
    tags: ["leaks", "database", "archive", "historical"],
  },
  {
    id: "18",
    name: "BreachForums",
    url: "https://breachforums.is",
    description: "Community for discussing data breaches and leaks. Share and discover breach information.",
    category: "Hacking Forums",
    tags: ["breach", "leaks", "community", "discussion"],
  },
  {
    id: "19",
    name: "Exploit.in",
    url: "https://exploit.in",
    description: "Russian-language forum for hackers and security researchers. Marketplace for exploits and tools.",
    category: "Hacking Forums",
    tags: ["russian", "exploits", "marketplace", "hacking"],
  },
  {
    id: "20",
    name: "XSS.is",
    url: "https://xss.is",
    description: "Cybersecurity forum and marketplace. Discussions on hacking, security, and vulnerability research.",
    category: "Hacking Forums",
    tags: ["security", "hacking", "marketplace", "research"],
  },
  {
    id: "40",
    name: "Darknet Army",
    url: "https://darknetarmy.com/",
    description: "Underground hacking and security forum. Community discussions on exploits, tools, and techniques.",
    category: "Hacking Forums",
    tags: ["hacking", "security", "community", "exploits"],
  },
  {
    id: "41",
    name: "Dark Forums",
    url: "https://darkforums.st/",
    description: "General purpose darknet forum. Discussions on hacking, carding, and underground activities.",
    category: "Hacking Forums",
    tags: ["darknet", "hacking", "carding", "community"],
  },
  {
    id: "42",
    name: "Altenens",
    url: "https://altenens.is/",
    description: "Premium account sharing and cracking forum. Marketplace for hacked accounts and tools.",
    category: "Hacking Forums",
    tags: ["accounts", "cracking", "marketplace", "sharing"],
  },
  {
    id: "43",
    name: "Savastan0",
    url: "https://savastan0.tools/",
    description: "Carding and fraud forum. Tools and resources for credit card fraud and financial crimes.",
    category: "Hacking Forums",
    tags: ["carding", "fraud", "tools", "financial"],
  },
  {
    id: "44",
    name: "LeakForum.st",
    url: "https://leakforum.st/",
    description: "Database leak and breach discussion forum. Share and discover leaked data and credentials.",
    category: "Hacking Forums",
    tags: ["leaks", "breach", "database", "credentials"],
  },
  {
    id: "45",
    name: "LeakForum.io",
    url: "https://leakforum.io/",
    description: "Alternative leak forum for data breaches. Community-driven breach sharing and discussion.",
    category: "Hacking Forums",
    tags: ["leaks", "breach", "community", "data"],
  },
  {
    id: "46",
    name: "Crackia",
    url: "https://crackia.com/",
    description: "Software cracking and reverse engineering forum. Share cracks, keygens, and tutorials.",
    category: "Hacking Forums",
    tags: ["cracking", "software", "reverse-engineering", "tools"],
  },
  {
    id: "47",
    name: "Cracking.org",
    url: "https://cracking.org/",
    description: "Password cracking and hash breaking community. Tools, wordlists, and cracking techniques.",
    category: "Hacking Forums",
    tags: ["password", "cracking", "hashing", "tools"],
  },
  {
    id: "48",
    name: "Sinister.ly",
    url: "https://sinister.ly/",
    description: "General hacking and security forum. Discussions on exploits, malware, and hacking techniques.",
    category: "Hacking Forums",
    tags: ["hacking", "security", "exploits", "malware"],
  },
  {
    id: "49",
    name: "Demon Forums",
    url: "https://demonforums.net/",
    description: "Multi-purpose underground forum. Hacking, gaming, marketplace, and general discussions.",
    category: "Hacking Forums",
    tags: ["hacking", "gaming", "marketplace", "community"],
  },
  {
    id: "50",
    name: "Voided",
    url: "https://voided.to/",
    description: "Premium cracking and leak forum. High-quality leaks, tools, and exclusive content.",
    category: "Hacking Forums",
    tags: ["cracking", "leaks", "premium", "exclusive"],
  },
  {
    id: "51",
    name: "Leaking.cc",
    url: "https://leaking.cc/",
    description: "Data leak and breach forum. Share databases, credentials, and breach information.",
    category: "Hacking Forums",
    tags: ["leaks", "breach", "database", "sharing"],
  },
  {
    id: "52",
    name: "Kitty Forums",
    url: "https://kittyforums.to/",
    description: "Community forum for hacking and security. Tutorials, tools, and marketplace.",
    category: "Hacking Forums",
    tags: ["hacking", "security", "tutorials", "marketplace"],
  },
  {
    id: "53",
    name: "Cracked.sh",
    url: "https://cracked.sh/",
    description: "Account cracking and combo list forum. Share and trade cracked accounts and tools.",
    category: "Hacking Forums",
    tags: ["cracking", "accounts", "combos", "trading"],
  },
  {
    id: "54",
    name: "HackForums",
    url: "https://hackforums.net/",
    description: "One of the oldest hacking forums. Discussions on coding, hacking, security, and marketplace.",
    category: "Hacking Forums",
    tags: ["hacking", "coding", "security", "marketplace"],
  },
  {
    id: "55",
    name: "Patched",
    url: "https://patched.to/",
    description: "Software patching and cracking forum. Share patches, cracks, and reverse engineering guides.",
    category: "Hacking Forums",
    tags: ["patching", "cracking", "software", "reverse-engineering"],
  },
  {
    id: "56",
    name: "Crackings.one",
    url: "https://crackings.one/",
    description: "Cracking and hacking community. Tools, tutorials, and marketplace for digital goods.",
    category: "Hacking Forums",
    tags: ["cracking", "hacking", "tools", "marketplace"],
  },
  {
    id: "92",
    name: "BreachStars",
    url: "https://breachsta.rs/",
    description: "Data breach search and leak database. Find compromised credentials and breach information.",
    category: "Hacking Forums",
    tags: ["breach", "leaks", "database", "credentials"],
  },

  // DARKWEB RESEARCH SITES
  {
    id: "11",
    name: "Ahmia",
    url: "https://ahmia.fi",
    description: "Tor hidden service search engine. Discover and search .onion sites on the darkweb safely.",
    category: "Darkweb Research",
    tags: ["tor", "onion", "search", "darknet"],
  },
  {
    id: "12",
    name: "Torch",
    url: "http://torchdeedp3i2jigzjdmfpn5ttjhthh5wbmda2rr3jvqjg5p77c54dqd.onion",
    description: "Oldest and most popular darkweb search engine. Index of millions of .onion pages.",
    category: "Darkweb Research",
    tags: ["search", "tor", "onion", "index"],
  },
  {
    id: "13",
    name: "Dark.fail",
    url: "https://dark.fail",
    description: "Verified list of darknet market URLs and mirrors. Stay updated on market status and avoid phishing.",
    category: "Darkweb Research",
    tags: ["markets", "verification", "mirrors", "safety"],
  },
  {
    id: "14",
    name: "Onion.live",
    url: "https://onion.live",
    description: "Directory of verified .onion links. Browse categories including markets, forums, and services.",
    category: "Darkweb Research",
    tags: ["directory", "onion", "links", "verified"],
  },
  {
    id: "15",
    name: "Tor66",
    url: "http://tor66sewebgixwhcqfnp5inzp5x5uohhdy3kvtnyfxc2e5mxiuh34iid.onion",
    description: "Fresh darkweb search engine with updated index. Find hidden services and onion sites.",
    category: "Darkweb Research",
    tags: ["search", "tor", "onion", "fresh"],
  },
  {
    id: "38",
    name: "Haystak",
    url: "http://haystak5njsmn2hqkewecpaxetahtwhsbsa64jom2k22z5afxhnpxfid.onion",
    description: "Darknet search engine with over 1.5 billion indexed pages. Fast and reliable onion search.",
    category: "Darkweb Research",
    tags: ["search", "tor", "onion", "index"],
  },
  {
    id: "39",
    name: "DarkSearch",
    url: "https://darksearch.io",
    description: "Clearnet interface for searching the darkweb. Access .onion content without Tor browser.",
    category: "Darkweb Research",
    tags: ["search", "clearnet", "onion", "proxy"],
  },

  // SOCIAL MEDIA OSINT
  {
    id: "21",
    name: "Sherlock",
    url: "https://github.com/sherlock-project/sherlock",
    description: "Hunt down social media accounts by username across 300+ social networks. Open-source Python tool.",
    category: "Social Media OSINT",
    tags: ["username", "social", "search", "tool"],
  },
  {
    id: "22",
    name: "Social-Analyzer",
    url: "https://github.com/qeeqbox/social-analyzer",
    description: "Analyze and find profiles across 400+ social media platforms. Advanced username enumeration.",
    category: "Social Media OSINT",
    tags: ["analysis", "profiles", "enumeration", "social"],
  },
  {
    id: "23",
    name: "Twint",
    url: "https://github.com/twintproject/twint",
    description: "Advanced Twitter scraping tool. Gather tweets, followers, and user information without API limits.",
    category: "Social Media OSINT",
    tags: ["twitter", "scraping", "osint", "tool"],
  },
  {
    id: "24",
    name: "InstaLoader",
    url: "https://github.com/instaloader/instaloader",
    description: "Download Instagram photos, videos, stories, and metadata. Profile analysis and archiving tool.",
    category: "Social Media OSINT",
    tags: ["instagram", "download", "scraping", "archive"],
  },
  {
    id: "67",
    name: "ODCrawler",
    url: "https://odcrawler.xyz/",
    description: "OnlyFans data crawler and search engine. Find and analyze OnlyFans creator profiles and content.",
    category: "Social Media OSINT",
    tags: ["onlyfans", "crawler", "search", "profiles"],
  },
  {
    id: "68",
    name: "Epieos",
    url: "https://epieos.com/",
    description: "Email and social media OSINT tool. Reverse lookup for email addresses across multiple platforms.",
    category: "Social Media OSINT",
    tags: ["email", "reverse-lookup", "social", "investigation"],
  },
  {
    id: "69",
    name: "WhatsMyName",
    url: "https://www.whatsmyname.app/",
    description: "Username enumeration across 600+ websites. Check username availability and find social profiles.",
    category: "Social Media OSINT",
    tags: ["username", "enumeration", "search", "profiles"],
  },

  // DOMAIN & NETWORK INTELLIGENCE
  {
    id: "25",
    name: "SecurityTrails",
    url: "https://securitytrails.com",
    description: "Historical DNS data and domain intelligence. Track domain changes, subdomains, and infrastructure.",
    category: "Domain & Network Intel",
    tags: ["dns", "domain", "history", "tracking"],
  },
  {
    id: "26",
    name: "VirusTotal",
    url: "https://www.virustotal.com",
    description:
      "Analyze suspicious files, URLs, domains, and IP addresses. Aggregate data from 70+ antivirus scanners.",
    category: "Domain & Network Intel",
    tags: ["malware", "scanning", "analysis", "security"],
  },
  {
    id: "27",
    name: "URLScan.io",
    url: "https://urlscan.io",
    description: "Website scanner and analysis tool. Capture screenshots, analyze resources, and detect threats.",
    category: "Domain & Network Intel",
    tags: ["scanning", "analysis", "threats", "website"],
  },
  {
    id: "28",
    name: "Whois Lookup",
    url: "https://whois.domaintools.com",
    description:
      "Domain registration information lookup. Find registrant details, nameservers, and registration history.",
    category: "Domain & Network Intel",
    tags: ["whois", "domain", "registration", "lookup"],
  },

  // GEOLOCATION & MAPPING
  {
    id: "29",
    name: "Google Earth",
    url: "https://earth.google.com",
    description: "Satellite imagery and 3D terrain visualization. Historical imagery and street view integration.",
    category: "Geolocation Tools",
    tags: ["satellite", "mapping", "imagery", "location"],
  },
  {
    id: "30",
    name: "Wigle",
    url: "https://wigle.net",
    description:
      "Wireless network mapping database. Find WiFi networks, cell towers, and Bluetooth devices by location.",
    category: "Geolocation Tools",
    tags: ["wifi", "wireless", "mapping", "location"],
  },
  {
    id: "72",
    name: "Picarta.ai",
    url: "https://picarta.ai/",
    description:
      "AI-powered geolocation tool. Identify locations from images using artificial intelligence and visual recognition.",
    category: "Geolocation Tools",
    tags: ["ai", "image", "geolocation", "recognition"],
  },

  // PEOPLE SEARCH & INVESTIGATION
  {
    id: "31",
    name: "Pipl",
    url: "https://pipl.com",
    description: "Deep web people search engine. Find contact information, social profiles, and public records.",
    category: "People Search",
    tags: ["people", "search", "contact", "records"],
  },
  {
    id: "32",
    name: "TruePeopleSearch",
    url: "https://www.truepeoplesearch.com",
    description: "Free people search with phone numbers, addresses, and relatives. US-focused public records.",
    category: "People Search",
    tags: ["people", "phone", "address", "records"],
  },
  {
    id: "70",
    name: "IntelTechniques Name Search",
    url: "https://inteltechniques.com/tools/Name.html",
    description: "Comprehensive name search tool by Michael Bazzell. Search across multiple databases and platforms.",
    category: "People Search",
    tags: ["name", "search", "comprehensive", "investigation"],
  },
  {
    id: "71",
    name: "192.com",
    url: "https://www.192.com/",
    description:
      "UK-based people finder and directory. Search for people, addresses, phone numbers, and businesses in the UK.",
    category: "People Search",
    tags: ["uk", "people", "directory", "address", "phone"],
  },
  {
    id: "73",
    name: "10digits",
    url: "http://10digits.us/",
    description:
      "US phone number lookup and reverse search. Find owner information and location data from phone numbers.",
    category: "People Search",
    tags: ["phone", "lookup", "us", "reverse-search"],
  },
  {
    id: "74",
    name: "ThatsThem",
    url: "http://thatsthem.com/",
    description: "Free people search with reverse phone, email, and address lookup. Comprehensive US public records.",
    category: "People Search",
    tags: ["people", "phone", "email", "address", "reverse-lookup"],
  },
  {
    id: "75",
    name: "Yellow Pages",
    url: "http://www.yellowpages.com/",
    description: "Business and residential directory. Find people, phone numbers, addresses, and local businesses.",
    category: "People Search",
    tags: ["directory", "phone", "business", "address"],
  },
  {
    id: "76",
    name: "White Pages",
    url: "http://www.whitepages.com/",
    description: "Leading people search engine. Find phone numbers, addresses, background checks, and public records.",
    category: "People Search",
    tags: ["people", "phone", "address", "background-check"],
  },
  {
    id: "77",
    name: "US Search",
    url: "http://www.ussearch.com/",
    description:
      "Premium people search and background check service. Access public records, criminal history, and more.",
    category: "People Search",
    tags: ["people", "background-check", "records", "premium"],
  },
  {
    id: "78",
    name: "FoneFinder",
    url: "https://www.fonefinder.net/",
    description: "Phone number lookup and carrier identification. Find phone owner details and service provider info.",
    category: "People Search",
    tags: ["phone", "lookup", "carrier", "identification"],
  },
  {
    id: "79",
    name: "Lullar",
    url: "https://com.lullar.com/",
    description: "Email and username search tool. Find social media profiles and online presence from email addresses.",
    category: "People Search",
    tags: ["email", "username", "social", "search"],
  },
  {
    id: "80",
    name: "Address Search",
    url: "https://email.addresssearch.com/",
    description: "Email address search and verification. Find email owners and validate email addresses.",
    category: "People Search",
    tags: ["email", "verification", "search", "validation"],
  },
  {
    id: "81",
    name: "Canada411",
    url: "https://www.canada411.ca/",
    description: "Canadian phone directory and people search. Find phone numbers, addresses, and businesses in Canada.",
    category: "People Search",
    tags: ["canada", "phone", "directory", "address"],
  },
  {
    id: "82",
    name: "PeekYou UK",
    url: "https://www.peekyou.com/united_kingdom",
    description: "UK people search engine. Find social profiles, contact information, and public records in the UK.",
    category: "People Search",
    tags: ["uk", "people", "social", "search"],
  },
  {
    id: "83",
    name: "Webmii",
    url: "https://webmii.com/",
    description: "People search aggregator. Find online presence, social profiles, and web mentions across platforms.",
    category: "People Search",
    tags: ["people", "aggregator", "social", "web-presence"],
  },
  {
    id: "84",
    name: "Ratsit",
    url: "https://www.ratsit.se/",
    description:
      "Swedish people and business search. Find personal information, addresses, and company data in Sweden.",
    category: "People Search",
    tags: ["sweden", "people", "business", "directory"],
  },
  {
    id: "85",
    name: "De Gule Sider",
    url: "https://www.degulesider.dk/",
    description: "Danish phone directory and people search. Find phone numbers, addresses, and businesses in Denmark.",
    category: "People Search",
    tags: ["denmark", "phone", "directory", "address"],
  },
  {
    id: "86",
    name: "Find Person Germany",
    url: "https://find-person-germany.com/",
    description: "German people search engine. Find contact information and addresses for people in Germany.",
    category: "People Search",
    tags: ["germany", "people", "search", "address"],
  },
  {
    id: "87",
    name: "GoYellow Germany",
    url: "https://www.goyellow.de/",
    description: "German business and people directory. Find phone numbers, addresses, and company information.",
    category: "People Search",
    tags: ["germany", "business", "directory", "phone"],
  },
  {
    id: "88",
    name: "All Area Codes",
    url: "https://www.allareacodes.com/area-code-lookup/",
    description: "US area code lookup and phone number search. Identify location and carrier from area codes.",
    category: "People Search",
    tags: ["area-code", "phone", "lookup", "us"],
  },
  {
    id: "89",
    name: "Melissa Lookups",
    url: "https://www.melissa.com/",
    description: "Address verification and data quality tools. Validate addresses, phone numbers, and email addresses.",
    category: "People Search",
    tags: ["verification", "address", "phone", "email", "validation"],
  },
  {
    id: "90",
    name: "US Zip Codes",
    url: "https://www.unitedstateszipcodes.org/",
    description:
      "US zip code lookup and geographic data. Find zip codes, cities, counties, and demographic information.",
    category: "People Search",
    tags: ["zipcode", "us", "geographic", "lookup"],
  },

  // CRYPTOCURRENCY TRACKING
  {
    id: "33",
    name: "Blockchain Explorer",
    url: "https://www.blockchain.com/explorer",
    description: "Bitcoin and cryptocurrency blockchain explorer. Track transactions, addresses, and wallet activity.",
    category: "Crypto Tracking",
    tags: ["bitcoin", "blockchain", "tracking", "crypto"],
  },
  {
    id: "34",
    name: "Chainalysis",
    url: "https://www.chainalysis.com",
    description: "Blockchain analysis and investigation platform. Track illicit cryptocurrency transactions.",
    category: "Crypto Tracking",
    tags: ["analysis", "investigation", "blockchain", "tracking"],
  },
]

export const categories = [
  "All",
  "OSINT Search Engines",
  "Breach Sites",
  "Darkweb Research",
  "Hacking Forums",
  "Social Media OSINT",
  "Domain & Network Intel",
  "Geolocation Tools",
  "People Search",
  "Crypto Tracking",
]
